In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

In [7]:
df = pd.read_csv("student-mat.csv", sep=";")

In [8]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [9]:
le = LabelEncoder()

In [10]:
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

In [11]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,0,0,18,1,0,0,4,4,0,4,...,4,3,4,1,1,3,6,5,6,6
1,0,0,17,1,0,1,1,1,0,2,...,5,3,3,1,1,3,4,5,5,6
2,0,0,15,1,1,1,1,1,0,2,...,4,3,2,2,3,3,10,7,8,10
3,0,0,15,1,0,1,4,2,1,3,...,3,2,2,1,1,5,2,15,14,15
4,0,0,16,1,0,1,3,3,2,2,...,4,3,2,1,2,5,4,6,10,10

In [12]:
X = df.drop("G3", axis=1)
Y = df["G3"]

In [13]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [14]:
print(df.isnull().sum())

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [15]:
df = df.dropna()

In [16]:


X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

model = Sequential([
    Input(shape=(X_train.shape[1],)),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1)
])

model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

model.summary()

history = model.fit(
    X_train,
    Y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2
)

loss, mae = model.evaluate(X_test, Y_test)

print("\nTest MAE:", mae)

predictions = model.predict(X_test[:5])

for i in range(5):
    print(f"Actual Grade: {Y_test.iloc[i]}")
    print(f"Predicted Grade: {predictions[i][0]:.2f}")
    print("-" * 30)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,225 (16.50 KB)

 Trainable params: 4,225 (16.50 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 4s 137ms/step - loss: 136.3605 - mae: 10.7266 - val_loss: 128.3174 - val_mae: 10.5838
Epoch 2/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 125.4775 - mae: 10.2183 - val_loss: 118.3093 - val_mae: 10.1320
Epoch 3/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 115.7772 - mae: 9.8128 - val_loss: 108.8847 - val_mae: 9.7212
Epoch 4/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 106.3680 - mae: 9.4252 - val_loss: 99.2120 - val_mae: 9.2800
Epoch 5/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 96.1128 - mae: 8.9754 - val_loss: 88.8101 - val_mae: 8.7781
Epoch 6/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 85.2031 - mae: 8.4567 - val_loss: 77.3362 - val_mae: 8.1795
Epoch 7/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 72.9647 - mae: 7.8390 - val_loss: 65.1478 - val_mae: 7.4786
Epoch 8/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 60.2376 - mae: 7.1034 - val_loss: 52.4992 - val_mae: 6.6747
Epoch 9/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 47.2027 - mae: 6.2674 - val_loss: 40.2267 - val_mae: 5.7921
Epoch 10/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 35.2478 - mae: 5.3393 - val_loss: 29.2693 - val_mae: 4.8742
Epoch 11/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 24.7021 - mae: 4.3740 - val_loss: 20.9828 - val_mae: 4.0325
Epoch 12/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 17.1241 - mae: 3.5083 - val_loss: 15.7464 - val_mae: 3.3067
Epoch 13/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 12.7593 - mae: 2.8516 - val_loss: 13.1708 - val_mae: 2.8199
Epoch 14/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 10.6731 - mae: 2.5039 - val_loss: 12.1691 - val_mae: 2.6365
Epoch 15/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.3707 - mae: 2.2852 - val_loss: 11.7092 - val_mae: 2.5739
Epoch 16/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.4103 - mae: 2.1410 - val_loss: 11.3265 - val_mae: 2.5418
Epoch 17/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.6833 - mae: 2.0470 - val_loss: 10.8881 - val_mae: 2.5292
Epoch 18/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.0000 - mae: 1.9614 - val_loss: 10.5737 - val_mae: 2.5103
Epoch 19/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5352 - mae: 1.8929 - val_loss: 10.3097 - val_mae: 2.4900
Epoch 20/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1575 - mae: 1.8367 - val_loss: 10.0396 - val_mae: 2.4621
Epoch 21/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7978 - mae: 1.7855 - val_loss: 9.8721 - val_mae: 2.4360
Epoch 22/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.4971 - mae: 1.7415 - val_loss: 9.6825 - val_mae: 2.4087
Epoch 23/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.2452 - mae: 1.7045 - val_loss: 9.5637 - val_mae: 2.3885
Epoch 24/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0413 - mae: 1.6755 - val_loss: 9.3622 - val_mae: 2.3650
Epoch 25/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.8018 - mae: 1.6391 - val_loss: 9.2836 - val_mae: 2.3531
Epoch 26/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.6176 - mae: 1.6103 - val_loss: 9.1319 - val_mae: 2.3357
Epoch 27/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.4387 - mae: 1.5852 - val_loss: 9.0590 - val_mae: 2.3272
Epoch 28/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.2647 - mae: 1.5540 - val_loss: 8.9881 - val_mae: 2.3095
Epoch 29/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4.1082 - mae: 1.5235 - val_loss: 8.8486 - val_mae: 2.2901
Epoch 30/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.9648 - mae: 1.4980 - val_loss: 8.7364 - val_mae: 2.2778
Epoch 31/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.8205 - mae: 1.4715 - val_loss: 8.6285 - val_mae: 2.2625
Epoch 32/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.6894 - mae: 1.4483 - val_loss: 8.5601 - val_mae: 2.2571
Epoch 33/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.5553 - mae: 1.4230 - val_loss: 8.4877 - val_mae: 2.2437
Epoch 34/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.4320 - mae: 1.4000 - val_loss: 8.4233 - val_mae: 2.2325
Epoch 35/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.3195 - mae: 1.3744 - val_loss: 8.3720 - val_mae: 2.2267
Epoch 36/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.1973 - mae: 1.3457 - val_loss: 8.2950 - val_mae: 2.2124
Epoch 37/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.0880 - mae: 1.3230 - val_loss: 8.2239 - val_mae: 2.2097
Epoch 38/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.9747 - mae: 1.3002 - val_loss: 8.1213 - val_mae: 2.1958
Epoch 39/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.8733 - mae: 1.2753 - val_loss: 8.0606 - val_mae: 2.1847
Epoch 40/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.7555 - mae: 1.2479 - val_loss: 7.9755 - val_mae: 2.1736
Epoch 41/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 2.6589 - mae: 1.2216 - val_loss: 7.9182 - val_mae: 2.1696
Epoch 42/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.5597 - mae: 1.1966 - val_loss: 7.8615 - val_mae: 2.1625
Epoch 43/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.4695 - mae: 1.1724 - val_loss: 7.7976 - val_mae: 2.1478
Epoch 44/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.3819 - mae: 1.1510 - val_loss: 7.7378 - val_mae: 2.1420
Epoch 45/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.2898 - mae: 1.1248 - val_loss: 7.7102 - val_mae: 2.1314
Epoch 46/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.2007 - mae: 1.1008 - val_loss: 7.5761 - val_mae: 2.1099
Epoch 47/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.1219 - mae: 1.0758 - val_loss: 7.5179 - val_mae: 2.1059
Epoch 48/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.0454 - mae: 1.0569 - val_loss: 7.3964 - val_mae: 2.0865
Epoch 49/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.9597 - mae: 1.0324 - val_loss: 7.3390 - val_mae: 2.0789
Epoch 50/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.8898 - mae: 1.0103 - val_loss: 7.3115 - val_mae: 2.0761
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.6274 - mae: 1.8684

Test MAE: 1.8684349060058594
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
Actual Grade: 10
Predicted Grade: 8.35
------------------------------
Actual Grade: 12
Predicted Grade: 9.98
------------------------------
Actual Grade: 5
Predicted Grade: 1.94
------------------------------
Actual Grade: 10
Predicted Grade: 9.36
------------------------------
Actual Grade: 9
Predicted Grade: 9.11
------------------------------